# Generated by Django 5.1.5 on 2025-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
