# Generated by Django 5.1.5 on 2025-02-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='publish_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('Unpublish', 'unpublish')], default='published', max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
