# Generated by Django 5.1.5 on 2025-02-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_publish_date_post_publish_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publish', 'publish'), ('unpublish', 'Unpublish')], default='published', max_length=16),
        ),
    ]
