# Generated by Django 5.1.5 on 2025-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image_alter_post_publish_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('Unpublish', 'unpublish')], default='published', max_length=16),
        ),
    ]
