# Generated by Django 5.1.5 on 2025-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publish', 'publish'), ('Unpublish', 'unpublish')], default='published', max_length=16),
        ),
    ]
