# Generated by Django 5.1.5 on 2025-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publish', 'publish'), ('unpublish', 'Unpublish')], default='published', max_length=16),
        ),
    ]
